### ISSUE TITLE
Game fail [Error: Cannot load module ... ]

### ISSUE THREAD

**Issue by debone** [aurium/js-game-server#15]
![image](https://cloud.githubusercontent.com/assets/763457/9294883/d32acc3e-4430-11e5-8475-a1375ce358a3.png)

**Comment by MakeshiftMitten** [comment]
Same issue. Have you found a fix?

**Comment by debone** [comment]
Nope :/ Tried to change permissions, folders, paths... Nothing :(


On Mon, Aug 17, 2015 at 22:11 PM, MakeshiftMitten <notifications@github.com>
wrote:

Same issue. Have you found a fix?


—
Reply to this email directly or view it on GitHub
<https://github.com/aurium/js-game-server/issues/15#issuecomment-132015106>.










-- 
Sent from MetroMail

**Comment by ooflorent** [comment]
Can you share your game to see what fails?

**Comment by MakeshiftMitten** [comment]
Right now it's just the tutorial project with the first basic index.html mods, no socket stuff in there yet. If you want I can throw up my whole file structure, but all of the tests pass when I start it.

**Comment by MakeshiftMitten** [comment]
I'm headed out on vacation, has anyone had any luck with this? I relcloned and reinstalled to a different directory, same issue. Is there something I should be looking at on the install?

**Comment by ooflorent** [comment]
@aurium wrote this part. I don't know well how it works...

**Comment by aurium** [comment]
Hi folks,

The official repo is https://github.com/js13kGames/js-game-server

@ooflorent look at [sandboxer.js:55](https://github.com/js13kGames/js-game-server/blob/083893fdea71823900d254ce9b9721f9af302cc5/lib/sandboxer.js#L55). The `sandbox.load()` crash, so i believe this is an [external sandboxer](https://www.npmjs.com/package/sandboxer) problem. May be a Windows path problem.

I believe you already did the windows support, right? Did you push the update to https://www.npmjs.com/package/sandboxer? Then i can update the [dependency](https://github.com/js13kGames/js-game-server/blob/083893fdea71823900d254ce9b9721f9af302cc5/package.json#L26).

**Comment by sneakykoder** [comment]
Hi @aurium, so the page of "http://js13kgames.com/#server" is outdated ?, and by the way i made working this server only following the guide and solving the dependencies

**Comment by aurium** [comment]
@sneakykoder sorry about that. I will notify Andrzej. I believe he copy the last year rules.
Don't worry. There is no important changes.

**Comment by sneakykoder** [comment]
@aurium Thanks !

**Comment by ooflorent** [comment]
I've published sandoxer@0.2.0. @aurium

**Comment by aurium** [comment]
Thanks @ooflorent!
https://github.com/js13kGames/js-game-server is updated.

@debone is it ok now?

**Comment by debone** [comment]
@aurium yup! Now it's fine :+1:
